force-app/main/default/objects/JSON_to_Field_Mapping__mdt/JSON_to_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata type is used by JSONStringValueToFieldValueUtility, and defines the JSON key values, and what sObject fields they map to.</description>
    <label>JSON to Field Mapping</label>
    <pluralLabel>JSON to Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/JSON_to_Field_Mapping__mdt/fields/JSON_Key__c.field-meta.xml
<CustomField>
    <fullName>JSON_Key__c</fullName>
    <description>The Key Value in the JSON string</description>
    <label>JSON Key</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_to_Field_Mapping__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>JSON_to_Field_Mappings</relationshipLabel>
    <relationshipName>JSON_to_Field_Mappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/JSON_to_Field_Mapping__mdt/fields/sObject_Field__c.field-meta.xml
<CustomField>
    <fullName>sObject_Field__c</fullName>
    <description>The API Name of the sObject Field that the JSON value will be stored in. Note: This is case sensitive, E.g Name and name are two values.</description>
    <inlineHelpText>The API Name of the sObject Field that the JSON value will be stored in. Note: This is case sensitive, E.g Name and name are two values.</inlineHelpText>
    <label>sObject Field</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JSONStringValueToFieldValueUtility.cls
public without sharing class JSONStringValueToFieldValueUtility {
    
    //  TODO: Support for single records, and do we remove the sObjectType variable and detect from the records automatically?
    public static List<sObject> convertValuesForRecords(string sObjectType, List<sObject> records, string rawJSONField)
    {
        // Get the field mappings (stored as custom metadata) for objects invovled
        Map<String, String> fieldMappings = fieldMappingsForObject(sObjectType);
        
        for(sObject record : records)
        {
            // If the record(s) are not the correct type (not matching the sObjectType variable) then skip to the next record - this prevents mixed records being passed.
            if(record.getSObjectType().getDescribe().getName() == sObjectType)
            {
                // If the JSON Field on the objecft is blank, then skip the rest of the processing
                if(!String.isBlank((String)record.get(rawJSONField)))
                {
                    // Using the JSON class, take the JSON field and deserialise into Map<String, Object>
                    Map<String, Object> jsonAsMap = (Map<String, Object>) JSON.deserializeUntyped((String)record.get(rawJSONField)); // See: https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Json.htm#apex_System_Json_deserializeUntyped
                    for(string jsonKeyValueMapping : fieldMappings.keySet())
                    {
                        Object jsonValue = jsonAsMap.get(jsonKeyValueMapping);
                        // TODO: Validate data types
                        record.put(fieldMappings.get(jsonKeyValueMapping), (String)jsonValue);
                    }   
                }
                else
                {
                    // TODO: More error handling...
                    System.debug('The JSON Field is empty - nothing to process');
                } 
            }
            else
            {
                // TODO: More error handling...
                System.debug('The record in the list does not match the sObject type specified in the method');
            }
        }

        return records;
    }
    
    private static Map<String,String> fieldMappingsForObject(string sObjectType)
    {
        Map<String, String> fieldMappings = new Map<String, String>();
        
        List<JSON_to_Field_Mapping__mdt> rawMappings = [
            SELECT Object__c, JSON_Key__c, sObject_Field__c, Id 
            FROM JSON_to_Field_Mapping__mdt 
            WHERE Object__c = :sObjectType
            WITH SECURITY_ENFORCED
            LIMIT 555];
        
        for(JSON_to_Field_Mapping__mdt rawMapping : rawMappings)
        {
            fieldMappings.put(rawMapping.JSON_Key__c, rawMapping.sObject_Field__c);
        }

        return fieldMappings;
    }
}